<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\User\ProdukController;
use App\Http\Controllers\User\KeranjangController;
use App\Http\Controllers\User\TransaksiController;
use App\Http\Controllers\User\SewaController;
use App\Http\Controllers\User\ProfilController;
use App\Http\Controllers\User\NotifikasiController;

// Public routes
Route::get('/', [HomeController::class, 'index'])->name('home');

// Auth routes (generated by Breeze)
require __DIR__.'/auth.php';

// Admin routes group
Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    // Admin routes will be added later
});

// User routes group
Route::middleware(['auth'])->prefix('user')->name('user.')->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    // Produk
    Route::prefix('produk')->name('produk.')->group(function () {
        Route::get('/', [ProdukController::class, 'index'])->name('index');
        Route::get('/{slug}', [ProdukController::class, 'show'])->name('show');
        Route::get('/kategori/{slug}', [ProdukController::class, 'byKategori'])->name('kategori');
        Route::get('/cari', [ProdukController::class, 'search'])->name('search');
    });
    
    // Keranjang
    Route::prefix('keranjang')->name('keranjang.')->group(function () {
        Route::get('/', [KeranjangController::class, 'index'])->name('index');
        Route::post('/', [KeranjangController::class, 'store'])->name('store');
        Route::put('/{id}', [KeranjangController::class, 'update'])->name('update');
        Route::delete('/{id}', [KeranjangController::class, 'destroy'])->name('destroy');
        Route::post('/clear', [KeranjangController::class, 'clear'])->name('clear');
    });
    
    // Transaksi
    Route::prefix('transaksi')->name('transaksi.')->group(function () {
        Route::get('/', [TransaksiController::class, 'index'])->name('index');
        Route::get('/create', [TransaksiController::class, 'create'])->name('create');
        Route::post('/', [TransaksiController::class, 'store'])->name('store');
        Route::get('/{id}', [TransaksiController::class, 'show'])->name('show');
        Route::post('/{id}/upload-bukti', [TransaksiController::class, 'uploadBukti'])->name('upload-bukti');
        Route::post('/{id}/cancel', [TransaksiController::class, 'cancel'])->name('cancel');
    });
    
    // Sewa
    Route::prefix('sewa')->name('sewa.')->group(function () {
        Route::get('/', [SewaController::class, 'index'])->name('index');
        Route::get('/aktif', [SewaController::class, 'aktif'])->name('aktif');
        Route::get('/riwayat', [SewaController::class, 'riwayat'])->name('riwayat');
        Route::get('/{id}', [SewaController::class, 'show'])->name('show');
        Route::post('/{id}/pengembalian', [SewaController::class, 'pengembalian'])->name('pengembalian');
    });
    
    // Profil
Route::prefix('profil')->name('profil.')->group(function () {
    Route::get('/', [ProfilController::class, 'edit'])->name('edit');
    Route::put('/', [ProfilController::class, 'update'])->name('update');
    Route::get('/security', [ProfilController::class, 'security'])->name('security');
    Route::put('/security', [ProfilController::class, 'updateSecurity'])->name('update-security');
    Route::put('/avatar', [ProfilController::class, 'updateAvatar'])->name('update-avatar');
    Route::delete('/avatar', [ProfilController::class, 'deleteAvatar'])->name('delete-avatar');
    Route::get('/activity', [ProfilController::class, 'getActivity'])->name('activity'); // ← Hapus "get-" dari nama route
});
    
    // Notifikasi
// Dalam group user routes, tambahkan:

// Notifikasi API
Route::prefix('notifikasi')->name('notifikasi.')->group(function () {
    Route::get('/', [NotifikasiController::class, 'index'])->name('index');
    Route::post('/{id}/read', [NotifikasiController::class, 'markAsRead'])->name('read');
    Route::post('/mark-all-read', [NotifikasiController::class, 'markAllAsRead'])->name('mark-all-read');
    Route::delete('/{id}', [NotifikasiController::class, 'destroy'])->name('destroy');
    Route::post('/clear-all', [NotifikasiController::class, 'clearAll'])->name('clear-all');
    Route::get('/unread-count', [NotifikasiController::class, 'getUnreadCount'])->name('unread-count');
    Route::get('/latest', [NotifikasiController::class, 'getLatest'])->name('latest');
});
});