<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\User\ProdukController;
use App\Http\Controllers\Admin\ProdukController as AdminProdukController;
use App\Http\Controllers\User\KeranjangController;
use App\Http\Controllers\User\TransaksiController;
use App\Http\Controllers\Admin\TransaksiController as AdminTransaksiController;
use App\Http\Controllers\User\SewaController;
use App\Http\Controllers\Admin\SewaController as AdminSewaController;
use App\Http\Controllers\User\ProfilController;
use App\Http\Controllers\User\NotifikasiController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\DendaController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\SearchController as AdminSearchController;

// Public routes
Route::get('/', [HomeController::class, 'index'])->name('home');

// Auth routes (generated by Breeze)
require __DIR__.'/auth.php';

// Admin routes group - SEMUA DALAM BAHASA INDONESIA
Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    // Dashboard
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/chart-data', [DashboardController::class, 'chartData'])->name('dashboard.chart-data');
    Route::get('/dashboard/quick-stats', [DashboardController::class, 'quickStats'])->name('dashboard.quick-stats');
    Route::get('/dashboard/export', [DashboardController::class, 'export'])->name('dashboard.export');


    Route::get('/search', [AdminSearchController::class, 'index'])->name('search');
    
    // Produk Routes
    Route::resource('produk', AdminProdukController::class);
    Route::patch('produk/{produk}/toggle-status', [AdminProdukController::class, 'toggleStatus'])->name('produk.toggle-status');
    Route::post('produk/bulk-action', [AdminProdukController::class, 'bulkAction'])->name('produk.bulk-action');
    
    // Transaksi Routes
    Route::resource('transaksi', AdminTransaksiController::class);
    Route::patch('transaksi/{transaksi}/status', [AdminTransaksiController::class, 'updateStatus'])->name('transaksi.update-status');
    Route::get('transaksi/{transaksi}/invoice', [AdminTransaksiController::class, 'invoice'])->name('transaksi.invoice');
    Route::get('transaksi/{transaksi}/print', [AdminTransaksiController::class, 'print'])->name('transaksi.print');
    Route::get('transaksi/{transaksi}/print', [AdminTransaksiController::class, 'print'])->name('transaksi.print');
    Route::post('transaksi/{transaksi}/verify-payment', [AdminTransaksiController::class, 'verifyPayment'])->name('transaksi.verifyPayment');
    
    // TAMBAHKAN INI untuk Export
    Route::get('transaksi/export/excel', [AdminTransaksiController::class, 'exportExcel'])->name('transaksi.export.excel');
    Route::get('transaksi/export/pdf', [AdminTransaksiController::class, 'exportPDF'])->name('transaksi.export.pdf');
    Route::get('transaksi/export/csv', [AdminTransaksiController::class, 'exportCSV'])->name('transaksi.export.csv');

    // Sewa Routes
    Route::resource('sewa', AdminSewaController::class);
    Route::get('sewa/aktif', [AdminSewaController::class, 'aktif'])->name('sewa.aktif');
    Route::get('sewa/terlambat', [AdminSewaController::class, 'terlambat'])->name('sewa.terlambat');
    Route::patch('sewa/{sewa}/status', [AdminSewaController::class, 'updateStatus'])->name('sewa.update-status');
    Route::post('sewa/{sewa}/pengembalian', [AdminSewaController::class, 'pengembalian'])->name('sewa.pengembalian');
    
    // Denda Routes
    Route::resource('denda', DendaController::class);
    Route::get('denda/belum-bayar', [DendaController::class, 'belumBayar'])->name('denda.belum-bayar');
    Route::patch('denda/{denda}/status-pembayaran', [DendaController::class, 'updateStatusPembayaran'])->name('denda.update-status-pembayaran');
    
    // User Management Routes
    Route::resource('user', AdminUserController::class);
    Route::patch('user/{user}/toggle-status', [AdminUserController::class, 'toggleStatus'])->name('user.toggle-status');
    Route::patch('user/{user}/role', [AdminUserController::class, 'updateRole'])->name('user.update-role');

    Route::resource('kategori', AdminKategoriController::class);
    Route::get('kategori', [AdminKategoriController::class, 'index'])->name('admin.kategori.index');
    
    // Laporan Routes
    Route::prefix('laporan')->name('laporan.')->group(function () {
        Route::get('/', [LaporanController::class, 'index'])->name('index');
        Route::get('/penjualan', [LaporanController::class, 'penjualan'])->name('penjualan');
        Route::get('/penyewaan', [LaporanController::class, 'penyewaan'])->name('penyewaan');
        Route::get('/invoice/{id}', [LaporanController::class, 'invoice'])->name('invoice');
        Route::get('/invoice/{id}/print', [LaporanController::class, 'printInvoice'])->name('invoice.print');
        Route::get('/invoice/{id}/pdf', [LaporanController::class, 'downloadInvoicePdf'])->name('invoice.pdf');
        Route::get('/penjualan/pdf', [LaporanController::class, 'downloadSalesPdf'])->name('penjualan.pdf');
        Route::get('/penyewaan/pdf', [LaporanController::class, 'downloadRentalPdf'])->name('penyewaan.pdf');
        Route::get('/export/{type}', [LaporanController::class, 'exportExcel'])->name('export.excel');
    });
});

// User routes group - TETAP SAMA
Route::middleware(['auth'])->prefix('user')->name('user.')->group(function () {
    // Dashboard
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    
    // Produk
    Route::prefix('produk')->name('produk.')->group(function () {
        Route::get('/', [ProdukController::class, 'index'])->name('index');
        Route::get('/{slug}', [ProdukController::class, 'show'])->name('show');
        Route::get('/kategori/{slug}', [ProdukController::class, 'byKategori'])->name('kategori');
        Route::get('/cari', [ProdukController::class, 'search'])->name('search');
    });
    
    // Keranjang
    Route::prefix('keranjang')->name('keranjang.')->group(function () {
        Route::get('/', [KeranjangController::class, 'index'])->name('index');
        Route::post('/', [KeranjangController::class, 'store'])->name('store');
        Route::put('/{id}', [KeranjangController::class, 'update'])->name('update');
        Route::delete('/{id}', [KeranjangController::class, 'destroy'])->name('destroy');
        Route::post('/clear', [KeranjangController::class, 'clear'])->name('clear');
    });
    
    // Transaksi
    Route::prefix('transaksi')->name('transaksi.')->group(function () {
        Route::get('/', [TransaksiController::class, 'index'])->name('index');
        Route::get('/create', [TransaksiController::class, 'create'])->name('create');
        Route::post('/', [TransaksiController::class, 'store'])->name('store');
        Route::get('/{id}', [TransaksiController::class, 'show'])->name('show');
        Route::post('/{id}/upload-bukti', [TransaksiController::class, 'uploadBukti'])->name('upload-bukti');
        Route::post('/{id}/cancel', [TransaksiController::class, 'cancel'])->name('cancel');
    });
    
    // Sewa
    Route::prefix('sewa')->name('sewa.')->group(function () {
        Route::get('/', [SewaController::class, 'index'])->name('index');
        Route::get('/aktif', [SewaController::class, 'aktif'])->name('aktif');
        Route::get('/riwayat', [SewaController::class, 'riwayat'])->name('riwayat');
        Route::get('/{id}', [SewaController::class, 'show'])->name('show');
        Route::post('/{id}/pengembalian', [SewaController::class, 'pengembalian'])->name('pengembalian');
    });
    
    // Profil
    Route::prefix('profil')->name('profil.')->group(function () {
        Route::get('/', [ProfilController::class, 'edit'])->name('edit');
        Route::put('/', [ProfilController::class, 'update'])->name('update');
        Route::get('/security', [ProfilController::class, 'security'])->name('security');
        Route::put('/security', [ProfilController::class, 'updateSecurity'])->name('update-security');
        Route::put('/avatar', [ProfilController::class, 'updateAvatar'])->name('update-avatar');
        Route::delete('/avatar', [ProfilController::class, 'deleteAvatar'])->name('delete-avatar');
        Route::get('/activity', [ProfilController::class, 'getActivity'])->name('activity');
    });
    
    // Notifikasi
    Route::prefix('notifikasi')->name('notifikasi.')->group(function () {
        Route::get('/', [NotifikasiController::class, 'index'])->name('index');
        Route::post('/{id}/read', [NotifikasiController::class, 'markAsRead'])->name('read');
        Route::post('/mark-all-read', [NotifikasiController::class, 'markAllAsRead'])->name('mark-all-read');
        Route::delete('/{id}', [NotifikasiController::class, 'destroy'])->name('destroy');
        Route::post('/clear-all', [NotifikasiController::class, 'clearAll'])->name('clear-all');
        Route::get('/unread-count', [NotifikasiController::class, 'getUnreadCount'])->name('unread-count');
        Route::get('/latest', [NotifikasiController::class, 'getLatest'])->name('latest');
    });
});

// Debug routes (optional, bisa dihapus jika tidak diperlukan)
Route::get('/debug-middleware', function() {
    $kernel = app(\App\Http\Kernel::class);
    $aliases = $kernel->getMiddlewareAliases();
    
    $adminExists = isset($aliases['admin']);
    $adminClass = $aliases['admin'] ?? 'NOT FOUND';
    
    return response()->json([
        'admin_middleware_registered' => $adminExists,
        'admin_middleware_class' => $adminClass,
        'file_exists' => file_exists(app_path('Http/Middleware/AdminMiddleware.php')),
        'class_exists' => class_exists($adminClass),
        'all_middleware_aliases' => array_keys($aliases),
    ]);
});

Route::middleware('admin')->get('/_debug/admin', function () {
    return 'ADMIN OK';
});